import {
    Archive,
    Armchair,
    Baby,
    Backpack,
    Bath,
    Bed,
    Bike,
    BookOpen,
    Boxes,
    Briefcase,
    Car,
    Container,
    DoorOpen,
    Dumbbell,
    Footprints,
    Gamepad2,
    Layers,
    type LucideIcon,
    Luggage,
    Monitor,
    Music,
    Package,
    PackageOpen,
    Palette,
    PawPrint,
    Refrigerator,
    Shirt,
    ShoppingBasket,
    Shovel,
    Snowflake,
    Sofa,
    Sprout,
    Tent,
    Toilet,
    Trees,
    Tv,
    Utensils,
    Warehouse,
    WashingMachine,
    Wine,
    Wrench,
} from 'lucide-vue-next';

export interface ItemIcon {
    value: string;
    label: string;
    icon: LucideIcon;
}

// Curated icons offered for rooms and containers (which rarely have a photo).
// Rooms/spaces first, then storage; `value` is stored on items.icon, so keep
// existing values stable when editing this list.
export const itemIcons: ItemIcon[] = [
    // Rooms & spaces
    { value: 'bed', label: 'Bedroom', icon: Bed },
    { value: 'sofa', label: 'Living room', icon: Sofa },
    { value: 'armchair', label: 'Lounge', icon: Armchair },
    { value: 'tv', label: 'TV room', icon: Tv },
    { value: 'utensils', label: 'Kitchen', icon: Utensils },
    { value: 'refrigerator', label: 'Pantry', icon: Refrigerator },
    { value: 'bath', label: 'Bathroom', icon: Bath },
    { value: 'toilet', label: 'Toilet', icon: Toilet },
    { value: 'briefcase', label: 'Office', icon: Briefcase },
    { value: 'book-open', label: 'Study', icon: BookOpen },
    { value: 'monitor', label: 'Media', icon: Monitor },
    { value: 'gamepad-2', label: 'Playroom', icon: Gamepad2 },
    { value: 'music', label: 'Music room', icon: Music },
    { value: 'palette', label: 'Craft room', icon: Palette },
    { value: 'baby', label: 'Nursery', icon: Baby },
    { value: 'shirt', label: 'Wardrobe', icon: Shirt },
    { value: 'door-open', label: 'Hallway', icon: DoorOpen },
    { value: 'footprints', label: 'Mudroom', icon: Footprints },
    { value: 'washing-machine', label: 'Laundry', icon: WashingMachine },
    { value: 'dumbbell', label: 'Gym', icon: Dumbbell },
    { value: 'paw-print', label: 'Pet area', icon: PawPrint },
    { value: 'wine', label: 'Wine cellar', icon: Wine },
    { value: 'car', label: 'Garage', icon: Car },
    { value: 'bike', label: 'Bike storage', icon: Bike },
    { value: 'wrench', label: 'Workshop', icon: Wrench },
    { value: 'warehouse', label: 'Basement', icon: Warehouse },
    { value: 'trees', label: 'Garden', icon: Trees },
    { value: 'sprout', label: 'Greenhouse', icon: Sprout },
    { value: 'shovel', label: 'Shed', icon: Shovel },
    { value: 'tent', label: 'Outdoor', icon: Tent },

    // Storage & containers
    { value: 'boxes', label: 'Shelf', icon: Boxes },
    { value: 'layers', label: 'Stack', icon: Layers },
    { value: 'package', label: 'Box', icon: Package },
    { value: 'package-open', label: 'Open box', icon: PackageOpen },
    { value: 'container', label: 'Bin', icon: Container },
    { value: 'shopping-basket', label: 'Basket', icon: ShoppingBasket },
    { value: 'archive', label: 'Drawer', icon: Archive },
    { value: 'backpack', label: 'Bag', icon: Backpack },
    { value: 'luggage', label: 'Suitcase', icon: Luggage },
    { value: 'snowflake', label: 'Freezer', icon: Snowflake },
];

export const itemIconMap: Record<string, LucideIcon> = Object.fromEntries(itemIcons.map((i) => [i.value, i.icon]));
